services:
  mongo:
    build:
      context: .
      dockerfile: backend/mongo/Dockerfile
    container_name: age-groups-mongo
    ports:
      - "27017:27017"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: age-groups-api
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=age_groups_db
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis

  redis:
    image: redis:7-alpine
    container_name: age-groups-redis
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: age-groups-worker
    command: python backend/worker/consumer_enrollment.py
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=age_groups_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - mongo

  frontend:
    image: python:3.11-slim
    container_name: age-groups-frontend
    working_dir: /app
    volumes:
      - ./:/app
    command: bash -c "pip install -r frontend/requirements.txt && streamlit run frontend/app.py --server.port=8501 --server.address=0.0.0.0"
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8501:8501"
    depends_on:
      - api

  test:
    build:
      context: ./backend/api/tests
      dockerfile: Dockerfile
    container_name: age-groups-test
    depends_on:
      - api
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=age_groups_db
      - REDIS_URL=redis://redis:6379/0
